#!/bin/bash
#Initialization
WORKING_DIRECTORY=$(echo $PWD)
echo 'Working directory is: '$WORKING_DIRECTORY

#MASTER parameters used across all models
INPUT_FILE='../../data/data_20230220.csv' #File to be converted in Convertool
#INPUT_FILE='../../convertool/test/test_input_long_1.csv' #File to be converted in Convertool

#Model estimation in batch

cd v3
cd Hosp65
rm *
../../convertool/bin/convertool $INPUT_FILE rinput.csv hO-i 2021-12-01 2023-02-20 65 333  > convertool.log
cp ../../workscript/cox_estimation_formulas.txt .
Rscript ../../workscript/Script.R rinput.csv Hospitalized Immunity  > script.log
../../clean 
cd ..



cd ..




echo 'Group done'
