#!/bin/bash
#Initialization
#WORKING_DIRECTORY=$(echo $PWD)
#echo 'Working directory is: '$WORKING_DIRECTORY

#MASTER parameters used across all models
INPUT_FILE='../../data/data_20230329.csv' #File to be converted in Convertool
#INPUT_FILE='../../convertool/test/test_input_long_1.csv' #File to be converted in Convertool

#Model estimation in batch

cd v3
mkdir $1
cd $1
rm *
../../convertool/bin/convertool $INPUT_FILE rinput.csv $2 $3 $4  > convertool.log
cp ../../workscript/cox_estimation_formulas.txt .
Rscript ../../workscript/Script.R rinput.csv $5  > script.log
rm temporary_full*.*
rm rinput.csv
cd ..




echo 'Group done'
