#!/bin/bash
#Initialization
#WORKING_DIRECTORY=$(echo $PWD)
#echo 'Working directory is: '$WORKING_DIRECTORY

#MASTER parameters used across all models
INPUT_FILE='../../data/data_20240527.csv' #File to be converted in Convertool

#Model estimation in batch

cd v3
mkdir $1
cd $1
rm *
../../convertool/bin/convertool $INPUT_FILE rinput.csv $2 $3 $4 $6 $7 > convertool.log
Rscript ../../workscript/Deaths.R rinput.csv $5  > Deaths.log
rm temporary_full*.*
rm rinput.csv
cd ..




echo 'Group done'
