#!/bin/bash
#Initialization
#WORKING_DIRECTORY=$(echo $PWD)
#echo 'Working directory is: '$WORKING_DIRECTORY

#MASTER parameters used across all models
INPUT_FILE='../../data/data_20230629.csv' #File to be converted in Convertool

#Model estimation in batch

cd v3
mkdir $1
cd $1
rm *
../../convertool/bin/convertool $INPUT_FILE rinput.csv $2 $3 $4 10 > convertool.log
Rscript ../../workscript/Script.R testrinput.csv $5  > script.log
rm temporary_full*.*
cd ..




echo 'Group done'
