#!/bin/bash
#Initialization
WORKING_DIRECTORY=$(echo $PWD)
echo 'Working directory is: '$WORKING_DIRECTORY

#MASTER parameters used across all models
#INPUT_FILE='../../data/data_20222006.csv' #File to be converted in Convertool
INPUT_FILE='../../convertool/test/test_input_long_1.csv' #File to be converted in Convertool

#Model estimation in batch

cd v3
cd Proxy
rm *
../../convertool/bin/convertool $INPUT_FILE rinput.csv xO-i 2021-12-01 2023-02-20  > convertool.log
cp ../../workscript/cox_estimation_formulas.txt .
Rscript ../../workscript/Script.R rinput.csv SeriousCovidProxy Immunity  > script.log
../../clean 
cd ..



cd ..




echo 'Group done'
