#!/bin/bash
#Initialization
#WORKING_DIRECTORY=$(echo $PWD)
#echo 'Working directory is: '$WORKING_DIRECTORY

#MASTER parameters used across all models
INPUT_FILE='../../data/data_20230629.csv' #File to be converted in Convertool

#Model estimation in batch

cd v3
mkdir infvacc
cd infvacc
rm *
../../convertool/bin/convertool $INPUT_FILE rinput.csv xx-icbs 2020-01-01 2023-06-29  > convertool.log
rm temporary_full*.*
rm rinput.csv
cd ..




echo 'Group done'
