#!/bin/bash
#Initialization
#WORKING_DIRECTORY=$(echo $PWD)
#echo 'Working directory is: '$WORKING_DIRECTORY

#MASTER parameters used across all models
#INPUT_FILE='../../data/data_20230329.csv' #File to be converted in Convertool
INPUT_FILE='../../data/data_20230421.csv' #File to be converted in Convertool
#INPUT_FILE='../../convertool/test/test_input_long_1.csv' #File to be converted in Convertool

#Model estimation in batch

cd v3
mkdir infvacc
cd infvacc
rm *
../../convertool/bin/convertool $INPUT_FILE rinput.csv xx-icbs 2020-01-01 2023-04-21  > convertool.log
rm temporary_full*.*
rm rinput.csv
cd ..




echo 'Group done'
