#!/bin/bash
SHORT=i:,m:,c:,f:,h
LONG=inputfile:,modelname:,ctooltype:,modelformula:,help
OPTS=$(getopt --options $SHORT --longoptions $LONG -- "$@")

eval set -- "$OPTS"

while :
do
  case "$1" in
    -i | --inputfile )
      INPUT_FILE="$2"
      shift 2
      ;;
    -m | --modelname )
      MODEL_NAME="$2"
      shift 2
      ;;
    -c | --ctooltype )
      CONVERTOOL_TYPE="$2"
      shift 2
      ;;
    -f | --modelformula )
      MODEL_FORMULA="$2"
      shift 2
      ;;
    -h | --help)
      "There is no help for you here."
      exit 2
      ;;
    --)
      shift;
      break
      ;;
    *)
      echo "Unexpected option: $1"
      ;;
  esac
done

echo "Starting to compute model "$MODEL_NAME
OUTPUTS_LOCATION=outputs/$MODEL_NAME/
rm $OUTPUTS_LOCATION/*
../convertool/bin/convertool $INPUT_FILE ../data/temp/$MODEL_NAME.csv $CONVERTOOL_TYPE > $OUTPUTS_LOCATION/convertool_log.txt
R < cox/cox_estimation.R --vanilla --args ../data/temp/$MODEL_NAME.csv $MODEL_FORMULA $OUTPUTS_LOCATION/convertool_log.txt > $OUTPUTS_LOCATION/r_log.txt
#rm ../data/temp/$MODEL_NAME.csv
#git add $OUTPUTS_LOCATION
#git commit -a --message="Run results: $MODEL_NAME"
#git pull --no-edit
#git push
exit 0
